name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/microservices-core-account
    container_name: dka-services-core-account-app
    hostname: account.core.services.dkaapis.com
    pull_policy: always
    restart: always
    environment:
      DKA_MONGO_HOST: dka-services-core-account-mongo
      DKA_SERVER_SECURE: false
    #ports:
      # expose by wan external public
      #- target: 50051
      #  published: 50051
      #  protocol: tcp
      #  host_ip: 0.0.0.0
      # expose by internal kubernetes
      #- target: 80
      #  published: 8081
      #  protocol: tcp
      #  host_ip: 0.0.0.0
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M
    networks:
      - dka-services-core-account
      - dka-development-network

  mongo:
    image: yovanggaanandhika/mongo:12-slim-mongo-8.0.5
    container_name: dka-services-core-account-mongo
    hostname: dka-services-core-account-mongo
    pull_policy: always
    restart: always
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 128M
          cpus: '0.5'
        limits:
          memory: 512M
          cpus: '0.8'
    volumes:
      - type: volume
        source: dka-services-core-account-mongo-data
        target: /data/db
    networks:
      - dka-services-core-account

volumes:
  dka-services-core-account-mongo-data:
    name : dka-services-core-account-mongo-data
    driver: local

networks:
  dka-services-core-account:
    driver: bridge
  dka-development-network:
    name: dka-development-network
    external: true