name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/services:core-account
    container_name: dka-services-core-account-app
    hostname: account.core.services.dkaapis.com
    environment:
      DKA_MONGO_HOST: dka-services-core-account-mongo
      DKA_SERVER_SECURE: false
    ports:
      - target: 80
        published: 80
        protocol: tcp
        host_ip: 0.0.0.0
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M
    networks:
      - dka-dev

  mongo:
    image: yovanggaanandhika/mongo:12-slim-mongo-8.0.5
    container_name: dka-services-core-account-mongo
    hostname: dka-services-core-account-mongo
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 128M
          cpus: '0.5'
        limits:
          memory: 512M
          cpus: '0.8'
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    networks:
      - dka-dev

volumes:
  mongo:
    driver: local

networks:
  dka-dev:
    driver: bridge
    external: true
