name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/microservices-core:account
    container_name: dka-services-core-account-app
    hostname: dka-services-core-account-app
    pull_policy: always
    restart: always
    environment:
      DKA_REPL_ENABLED: true
      DKA_MONGO_HOST: dka-dev-mongo
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 800M
    ports:
      # expose by wan external public
      - target: 50051
        published: 50051
        protocol: tcp
        host_ip: 0.0.0.0
    networks:
      - dka-development-network

networks:
  dka-development-network:
    name: dka-development-network
    external: true