name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/services:core-account
    container_name: dka-services-core-account-app
    hostname: dka-services-core-account-app
    environment:
      DKA_MONGO_HOST: dka-services-core-account-mongo
      DKA_SERVER_CERT_ALT_NAMES: dns1.dkaapis.com,dns2.dkaapis.com
      DKA_SERVER_SECURE: true
    ports:
      - target: 443
        published: 443
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: bind
        source: /var/tmp/account
        target: /var/tmp/account
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M
    networks:
      - dka-dev

  mongo:
    image: yovanggaanandhika/mongo:12-slim
    container_name: dka-services-core-account-mongo
    hostname: dka-services-core-account-mongo
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 128M
          cpus: '0.5'
        limits:
          memory: 512M
          cpus: '0.8'
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    networks:
      - dka-dev

volumes:
  mongo:
    driver: local

networks:
  dka-dev:
    driver: bridge
    external: true
