name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/node:latest
    container_name: dka-services-core-account-app
    hostname: dka-services-core-account-app
    environment:
      DKA_MONGO_HOST: dka-services-core-account-mongo
    ports:
      # expose by wann external public
      - target: 80
        published: 8081
        protocol: tcp
        host_ip: 0.0.0.0
      #expose by internal kubernetes
      - target: 63300
        published: 63300
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: bind
        source: .
        target: /home/app
    deploy:
      resources:
        reservations:
          memory: 1028M
        limits:
          memory: 2048M
    command: yarn run start:dev
    networks:
      - dka-services-core-account

  mongo:
    image: yovanggaanandhika/mongo:12-slim-mongo-8.0.5
    container_name: dka-services-core-account-mongo
    hostname: dka-services-core-account-mongo
    environment:
      DKA_REPL_ENABLED: true
    deploy:
      resources:
        reservations:
          memory: 128M
          cpus: '0.5'
        limits:
          memory: 512M
          cpus: '0.8'
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: volume
        source: dka-services-core-account-mongo-data
        target: /data/db
    networks:
      - dka-services-core-account

volumes:
  dka-services-core-account-mongo-data:
    name : dka-services-core-account-mongo-data
    driver: local

networks:
  dka-services-core-account:
    driver: bridge
