name: dka-services-core-account

services:
  app:
    image: yovanggaanandhika/node:latest
    container_name: dka-services-core-account-app
    hostname: dka-services-core-account-app
    pull_policy: always
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    environment:
      DKA_MONGO_HOST: dka-dev-mongo
    ports:
      # expose by wann external public
      - target: 50051
        published: 50051
        protocol: tcp
        host_ip: 0.0.0.0
      #expose by internal kubernetes
      - target: 80
        published: 8081
        protocol: tcp
        host_ip: 0.0.0.0
    volumes:
      - type: tmpfs
        target: /home/app/dist
      - type: bind
        source: .
        target: /home/app
    deploy:
      resources:
        reservations:
          memory: 1028M
        limits:
          memory: 2048M
    command: yarn run start:dev
    networks:
      - dka-development-network


networks:
  dka-development-network:
    name: dka-development-network
    external: true
