apiVersion: v1
kind: Pod
metadata:
  name: database-core-account
  labels:
    app: database-core-account
spec:
  containers:
    - name: mongo
      image: yovanggaanandhika/mongo:12-slim-mongo-8.0.5
      imagePullPolicy: Always
      ports:
        - containerPort: 27017
      env:
        - name: DKA_REPL_ENABLED
          value: "true"
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      resources:
        requests:
          memory: 128Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 800m
  volumes:
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: database-core-account
spec:
  selector:
    app: database-core-account
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
