// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: src/model/proto/credential/account.credential.grpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "account.credential";

export interface IAccountCredentialParent {
  /** Document ID (_id in MongoDB) */
  id?:
    | string
    | undefined;
  /** Preference ObjectId (as string) */
  credential?:
    | string
    | undefined;
  /** Preference ObjectId (as string) */
  info?: string | undefined;
}

/** Defining the AccountCredential message based on the IAccountCredential model */
export interface IAccountCredential {
  /** Document ID (_id in MongoDB) */
  id?:
    | string
    | undefined;
  /** Preference ObjectId (as string) */
  preference?:
    | string
    | undefined;
  /** Parent ObjectId (as string) */
  parent?:
    | IAccountCredentialParent
    | undefined;
  /** First name as string */
  email: string;
  /** Last name as string */
  username: string;
  password?: string | undefined;
}

/** The response message containing an AccountCredential */
export interface AccountCredentialReadRequest {
}

export interface AccountCredentialAuthRequest {
  username: string;
  password: string;
}

export interface AccountCredentialAuthResponse {
  status: boolean;
  code: number;
  msg: string;
  data: IAccountCredential | undefined;
}

export interface AccountCredentialCreateResponse {
  status: boolean;
  code: number;
  msg: string;
  data: IAccountCredential | undefined;
}

export interface AccountCredentialReadResponse {
  status: boolean;
  code: number;
  msg: string;
  data: IAccountCredential[];
}

function createBaseIAccountCredentialParent(): IAccountCredentialParent {
  return { id: undefined, credential: undefined, info: undefined };
}

export const IAccountCredentialParent: MessageFns<IAccountCredentialParent> = {
  encode(message: IAccountCredentialParent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.credential !== undefined) {
      writer.uint32(18).string(message.credential);
    }
    if (message.info !== undefined) {
      writer.uint32(26).string(message.info);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IAccountCredentialParent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIAccountCredentialParent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.credential = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.info = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IAccountCredentialParent {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      credential: isSet(object.credential) ? globalThis.String(object.credential) : undefined,
      info: isSet(object.info) ? globalThis.String(object.info) : undefined,
    };
  },

  toJSON(message: IAccountCredentialParent): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.credential !== undefined) {
      obj.credential = message.credential;
    }
    if (message.info !== undefined) {
      obj.info = message.info;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IAccountCredentialParent>, I>>(base?: I): IAccountCredentialParent {
    return IAccountCredentialParent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IAccountCredentialParent>, I>>(object: I): IAccountCredentialParent {
    const message = createBaseIAccountCredentialParent();
    message.id = object.id ?? undefined;
    message.credential = object.credential ?? undefined;
    message.info = object.info ?? undefined;
    return message;
  },
};

function createBaseIAccountCredential(): IAccountCredential {
  return { id: undefined, preference: undefined, parent: undefined, email: "", username: "", password: undefined };
}

export const IAccountCredential: MessageFns<IAccountCredential> = {
  encode(message: IAccountCredential, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.preference !== undefined) {
      writer.uint32(18).string(message.preference);
    }
    if (message.parent !== undefined) {
      IAccountCredentialParent.encode(message.parent, writer.uint32(26).fork()).join();
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.username !== "") {
      writer.uint32(42).string(message.username);
    }
    if (message.password !== undefined) {
      writer.uint32(50).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IAccountCredential {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIAccountCredential();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.preference = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parent = IAccountCredentialParent.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IAccountCredential {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      preference: isSet(object.preference) ? globalThis.String(object.preference) : undefined,
      parent: isSet(object.parent) ? IAccountCredentialParent.fromJSON(object.parent) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
    };
  },

  toJSON(message: IAccountCredential): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.preference !== undefined) {
      obj.preference = message.preference;
    }
    if (message.parent !== undefined) {
      obj.parent = IAccountCredentialParent.toJSON(message.parent);
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IAccountCredential>, I>>(base?: I): IAccountCredential {
    return IAccountCredential.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IAccountCredential>, I>>(object: I): IAccountCredential {
    const message = createBaseIAccountCredential();
    message.id = object.id ?? undefined;
    message.preference = object.preference ?? undefined;
    message.parent = (object.parent !== undefined && object.parent !== null)
      ? IAccountCredentialParent.fromPartial(object.parent)
      : undefined;
    message.email = object.email ?? "";
    message.username = object.username ?? "";
    message.password = object.password ?? undefined;
    return message;
  },
};

function createBaseAccountCredentialReadRequest(): AccountCredentialReadRequest {
  return {};
}

export const AccountCredentialReadRequest: MessageFns<AccountCredentialReadRequest> = {
  encode(_: AccountCredentialReadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountCredentialReadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountCredentialReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): AccountCredentialReadRequest {
    return {};
  },

  toJSON(_: AccountCredentialReadRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountCredentialReadRequest>, I>>(base?: I): AccountCredentialReadRequest {
    return AccountCredentialReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountCredentialReadRequest>, I>>(_: I): AccountCredentialReadRequest {
    const message = createBaseAccountCredentialReadRequest();
    return message;
  },
};

function createBaseAccountCredentialAuthRequest(): AccountCredentialAuthRequest {
  return { username: "", password: "" };
}

export const AccountCredentialAuthRequest: MessageFns<AccountCredentialAuthRequest> = {
  encode(message: AccountCredentialAuthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountCredentialAuthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountCredentialAuthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountCredentialAuthRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: AccountCredentialAuthRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountCredentialAuthRequest>, I>>(base?: I): AccountCredentialAuthRequest {
    return AccountCredentialAuthRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountCredentialAuthRequest>, I>>(object: I): AccountCredentialAuthRequest {
    const message = createBaseAccountCredentialAuthRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseAccountCredentialAuthResponse(): AccountCredentialAuthResponse {
  return { status: false, code: 0, msg: "", data: undefined };
}

export const AccountCredentialAuthResponse: MessageFns<AccountCredentialAuthResponse> = {
  encode(message: AccountCredentialAuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== false) {
      writer.uint32(8).bool(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int64(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(26).string(message.msg);
    }
    if (message.data !== undefined) {
      IAccountCredential.encode(message.data, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountCredentialAuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountCredentialAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = IAccountCredential.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountCredentialAuthResponse {
    return {
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
      data: isSet(object.data) ? IAccountCredential.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: AccountCredentialAuthResponse): unknown {
    const obj: any = {};
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    if (message.data !== undefined) {
      obj.data = IAccountCredential.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountCredentialAuthResponse>, I>>(base?: I): AccountCredentialAuthResponse {
    return AccountCredentialAuthResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountCredentialAuthResponse>, I>>(
    object: I,
  ): AccountCredentialAuthResponse {
    const message = createBaseAccountCredentialAuthResponse();
    message.status = object.status ?? false;
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? IAccountCredential.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseAccountCredentialCreateResponse(): AccountCredentialCreateResponse {
  return { status: false, code: 0, msg: "", data: undefined };
}

export const AccountCredentialCreateResponse: MessageFns<AccountCredentialCreateResponse> = {
  encode(message: AccountCredentialCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== false) {
      writer.uint32(8).bool(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int64(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(26).string(message.msg);
    }
    if (message.data !== undefined) {
      IAccountCredential.encode(message.data, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountCredentialCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountCredentialCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = IAccountCredential.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountCredentialCreateResponse {
    return {
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
      data: isSet(object.data) ? IAccountCredential.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: AccountCredentialCreateResponse): unknown {
    const obj: any = {};
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    if (message.data !== undefined) {
      obj.data = IAccountCredential.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountCredentialCreateResponse>, I>>(base?: I): AccountCredentialCreateResponse {
    return AccountCredentialCreateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountCredentialCreateResponse>, I>>(
    object: I,
  ): AccountCredentialCreateResponse {
    const message = createBaseAccountCredentialCreateResponse();
    message.status = object.status ?? false;
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? IAccountCredential.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseAccountCredentialReadResponse(): AccountCredentialReadResponse {
  return { status: false, code: 0, msg: "", data: [] };
}

export const AccountCredentialReadResponse: MessageFns<AccountCredentialReadResponse> = {
  encode(message: AccountCredentialReadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== false) {
      writer.uint32(8).bool(message.status);
    }
    if (message.code !== 0) {
      writer.uint32(16).int64(message.code);
    }
    if (message.msg !== "") {
      writer.uint32(26).string(message.msg);
    }
    for (const v of message.data) {
      IAccountCredential.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountCredentialReadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountCredentialReadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data.push(IAccountCredential.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountCredentialReadResponse {
    return {
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => IAccountCredential.fromJSON(e)) : [],
    };
  },

  toJSON(message: AccountCredentialReadResponse): unknown {
    const obj: any = {};
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => IAccountCredential.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountCredentialReadResponse>, I>>(base?: I): AccountCredentialReadResponse {
    return AccountCredentialReadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountCredentialReadResponse>, I>>(
    object: I,
  ): AccountCredentialReadResponse {
    const message = createBaseAccountCredentialReadResponse();
    message.status = object.status ?? false;
    message.code = object.code ?? 0;
    message.msg = object.msg ?? "";
    message.data = object.data?.map((e) => IAccountCredential.fromPartial(e)) || [];
    return message;
  },
};

export interface AccountCredential {
  Create(request: IAccountCredential): Promise<AccountCredentialCreateResponse>;
  Read(request: AccountCredentialReadRequest): Promise<AccountCredentialReadResponse>;
  Auth(request: AccountCredentialAuthRequest): Promise<AccountCredentialAuthResponse>;
}

export const AccountCredentialServiceName = "account.credential.AccountCredential";
export class AccountCredentialClientImpl implements AccountCredential {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AccountCredentialServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.Read = this.Read.bind(this);
    this.Auth = this.Auth.bind(this);
  }
  Create(request: IAccountCredential): Promise<AccountCredentialCreateResponse> {
    const data = IAccountCredential.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => AccountCredentialCreateResponse.decode(new BinaryReader(data)));
  }

  Read(request: AccountCredentialReadRequest): Promise<AccountCredentialReadResponse> {
    const data = AccountCredentialReadRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Read", data);
    return promise.then((data) => AccountCredentialReadResponse.decode(new BinaryReader(data)));
  }

  Auth(request: AccountCredentialAuthRequest): Promise<AccountCredentialAuthResponse> {
    const data = AccountCredentialAuthRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Auth", data);
    return promise.then((data) => AccountCredentialAuthResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
