name: Action Stage CI/CD

on:
  push:
    branches:
      - stage

env:

  SSH_SERVER_HOST: ${{ secrets.DKA_SSH_SERVER_HOST }}
  SSH_SERVER_USERNAME: ${{ secrets.DKA_SSH_SERVER_USERNAME }}
  SSH_SERVER_PRIVATE_KEY: ${{ secrets.DKA_SSH_SERVER_PRIVATE_KEY }}
  SSH_SERVER_PORT: ${{ secrets.DKA_SSH_SERVER_PORT }}
  SSH_SERVER_PATH: ${{ secrets.DKA_SSH_SERVER_PATH }}

  SERVER_COMPOSE_FILE : compose.stage.yml

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code dari Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Template Compose file ke path Server di dalam server path
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_SERVER_HOST }}
          username: ${{ env.SSH_SERVER_USERNAME }}
          key: ${{ env.SSH_SERVER_PRIVATE_KEY }}
          port: ${{ env.SSH_SERVER_PORT }}
          source: ${{ env.SERVER_COMPOSE_FILE }}
          overwrite: true
          target: "./${{ env.SSH_SERVER_PATH }}"

      - name: Menuju Path Di Server, Memuat tar.gz ke system image docker, dan Jalankan Ulang dengan image baru
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_SERVER_HOST }}
          username: ${{ env.SSH_SERVER_USERNAME }}
          key: ${{ env.SSH_SERVER_PRIVATE_KEY }}
          port: ${{ env.SSH_SERVER_PORT }}
          script: |
            # Overide Server Path Yang dituju di dalam server production valid path
            cd "./${{ env.SSH_SERVER_PATH }}"
            # Start new containers
            docker compose -f ${{ env.SERVER_COMPOSE_FILE }} up -d --force-recreate

  clean:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Clean Dangling Image in Dev Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_SERVER_HOST }}
          username: ${{ env.SSH_SERVER_USERNAME }}
          key: ${{ env.SSH_SERVER_PRIVATE_KEY }}
          port: ${{ env.SSH_SERVER_PORT }}
          script: |
            docker image prune -f